#!/usr/bin/env bash
set -e
if [[ "$#" -lt 1 ]] || ! [[ -e "$1" ]]; then
  (>&2 echo "Usage: $0 file arg...")
  exit 1
fi

MKGO_CACHE="${MKGO_CACHE:=${HOME}/.mkgo/cache}" && mkdir -p "${MKGO_CACHE}"

compile() {
  cc "$1" -o "$2"
}

shebang() {
  [[ "$(head -c2 "${1}")" == "#!" ]]
}

_mktemp() {
  case $(uname -s) in
    Darwin) mktemp -t temp ;;
    Linux) mktemp ;;
    *) (>&2 echo "Unknown system '$(uname -s)', don't now how to _mktemp");
       exit 1 ;;
  esac
}

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

strip_shebang() {
  local tmp="${1}"
  if shebang "${1}"; then
    tmp="$(_mktemp).c"
    tail -n+2 "${1}" > $tmp
  fi
  echo "${tmp}"
}

SRC_FILE="$(realpath "${1}")"
SRC_BASENAME="${SRC_FILE##*/}"
SRC_NAME="${SRC_BASENAME%.*}"
STRIPPED_FILE="$(strip_shebang "${SRC_FILE}")"

CACHED_BIN="${MKGO_CACHE}/${SRC_FILE}/${SRC_NAME}"

if [[ !(-f "${CACHED_BIN}") || ("${CACHED_BIN}" -ot "${SRC_FILE}") ]]; then
  rm -rf "${MKGO_CACHE}/${SRC_FILE}"
  mkdir -p "${MKGO_CACHE}/${SRC_FILE}"
  compile "${STRIPPED_FILE}" "${CACHED_BIN}"
fi

shift && exec -a "${SRC_NAME}" "${CACHED_BIN}" "$@"
